---
language: bash
env:
  - SCRIPTS_ONLY=1
addons:
  apt:
    packages:
      - jq
      - shellcheck
before_script:
  - shellcheck **/*.sh
script:
  - ./install.sh
# TODO: add after_script
#

notifications:
  email: false
