---
language: bash
os:
  - osx
  - linux
env:
  - SCRIPTS_ONLY=1
  - SCRIPTS_ONLY=0
addons:
  apt:
    packages:
      - jq
      - shellcheck
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./scripts/travis/brew_install.sh; fi
before_script:
  - shellcheck **/*.sh
script:
  - ./install.sh
  - ./scripts/travis/after_script.sh

notifications:
  email: false
