---
language: bash
env:
  - SCRIPTS_ONLY=1
addons:
  apt:
    packages:
      - jq
      - shellcheck
before_script:
  - shellcheck **/*.sh
script:
  - ./install.sh
  - ./scripts/travis/after_script.sh

notifications:
  email: false
